/**
 * Mapeo emoji → icono lucide-react. Punto único de verdad para
 * el reemplazo de emojis del HTML original en el UI v2.
 */
import {
  Droplets,
  Sun,
  Eye,
  Store,
  Sprout,
  Globe2,
  TriangleAlert,
  ListChecks,
  Tag,
  House,
  Trees,
  Snowflake,
  Mountain,
  CloudRain,
  Cloud,
  Waves,
  CloudSun,
  Wheat,
  Leaf,
  Flower,
  Flower2,
  Apple,
  TreePalm,
  Search,
  Share2,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  Check,
  X,
  CheckSquare,
  Circle,
  TrendingUp,
  BarChart3,
  Lightbulb,
  Bug,
  Skull,
  Wind,
  PocketKnife,
  Clock,
  Sunrise,
  Sunset,
  ArrowRight,
  Map,
  Hash,
  Zap,
  Gift,
  Phone,
  Heart,
  Bird,
  Pin,
  Smartphone,
  RefreshCw,
  Package,
  ClipboardList,
  Megaphone,
  CircleDollarSign,
  Thermometer,
  Hand,
  Calendar,
  Filter,
  Flame,
  Menu,
  type LucideIcon,
} from 'lucide-react';

export const Icons = {
  drop: Droplets,
  sun: Sun,
  eye: Eye,
  store: Store,
  sprout: Sprout,
  globe: Globe2,
  alert: TriangleAlert,
  alertCircle: Circle,
  checklist: ListChecks,
  tag: Tag,
  home: House,
  tree: Trees,
  snow: Snowflake,
  mountain: Mountain,
  cloudRain: CloudRain,
  cloud: Cloud,
  waves: Waves,
  cloudSun: CloudSun,
  wheat: Wheat,
  leaf: Leaf,
  flower: Flower,
  flower2: Flower2,
  fruit: Apple,
  palm: TreePalm,
  search: Search,
  share: Share2,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  check: Check,
  x: X,
  checkSquare: CheckSquare,
  trending: TrendingUp,
  chart: BarChart3,
  bulb: Lightbulb,
  bug: Bug,
  skull: Skull,
  wind: Wind,
  knife: PocketKnife,
  clock: Clock,
  sunrise: Sunrise,
  sunset: Sunset,
  arrowRight: ArrowRight,
  map: Map,
  hash: Hash,
  zap: Zap,
  gift: Gift,
  phone: Phone,
  heart: Heart,
  bird: Bird,
  pin: Pin,
  phoneSmart: Smartphone,
  refresh: RefreshCw,
  package: Package,
  clipboard: ClipboardList,
  megaphone: Megaphone,
  money: CircleDollarSign,
  thermometer: Thermometer,
  hand: Hand,
  calendar: Calendar,
  filter: Filter,
  flame: Flame,
  menu: Menu,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof Icons;

export const emojiToIcon: Record<string, IconName> = {
  '💧': 'drop',
  '☀️': 'sun',
  '🌞': 'sun',
  '👀': 'eye',
  '🏪': 'store',
  '🌱': 'sprout',
  '🌍': 'globe',
  '⚠️': 'alert',
  '📋': 'checklist',
  '🏷️': 'tag',
  '🏠': 'home',
  '🌳': 'tree',
  '❄️': 'snow',
  '⛰️': 'mountain',
  '🌧️': 'cloudRain',
  '🌊': 'waves',
  '🌤️': 'cloudSun',
  '🌵': 'wheat',
  '🌿': 'leaf',
  '🌸': 'flower',
  '🌺': 'flower2',
  '🌷': 'flower',
  '🍋': 'fruit',
  '🌴': 'palm',
  '✅': 'check',
  '❌': 'x',
  '📍': 'pin',
  '📱': 'phoneSmart',
  '💡': 'bulb',
  '🔄': 'refresh',
  '📦': 'package',
  '🪧': 'megaphone',
  '📊': 'chart',
  '⏱️': 'clock',
  '💰': 'money',
  '🌡️': 'thermometer',
  '🚰': 'drop',
  '🧹': 'knife',
  '🐛': 'bug',
  '🪲': 'bug',
  '🦠': 'bug',
  '💀': 'skull',
  '⚡': 'zap',
  '🦢': 'bird',
  '❤️': 'heart',
  '🔴': 'flower',
  '🟡': 'alertCircle',
  '🟤': 'alertCircle',
  '🟠': 'alertCircle',
  '🟢': 'check',
  '🔵': 'alertCircle',
  '⬛': 'skull',
  '🍂': 'leaf',
  '🚨': 'alert',
  '🧱': 'package',
  '🪴': 'sprout',
  '🪝': 'tag',
  '🪣': 'package',
  '🔥': 'flame',
};

export type ZonaClimaticaKey =
  | 'desertico'
  | 'semiarido'
  | 'costero'
  | 'templado'
  | 'montana'
  | 'frio-humedo';

export const zonaIcon: Record<ZonaClimaticaKey, IconName> = {
  desertico: 'sun',
  semiarido: 'wheat',
  costero: 'waves',
  templado: 'cloudSun',
  montana: 'mountain',
  'frio-humedo': 'cloudRain',
};
